### ISSUE TITLE
Not working on Linux Debian (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by KarboXXX** [ThePridestalker/OsuBackUp#16]
Sure it was probably meant to run on Windows 8.1+ machines only, but building this package on Debian works pretty well, surprisingly, a message appears asking me if i want to download it on my system, so i don't need to worry about the `.AppImage` path to open the app. I'll take some time to make it work. I can't make the maps' list, but it opens without any errors besides the `contextIsolation`, which made me surprised. (the following)

```
(node:38715) electron: The default of contextIsolation is deprecated and will be changing from
false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506
for more information
```

**NOTE:** do not run the `.AppImage` with root privileges or with sudo, it will likely break your path, since the instructions on the project that work on windows, are deprecated on Linux (ubuntu at least).

### Setup info (help to reproduce on a VM)
Distro: Ubuntu 20.04 LTS
CPU: 2Ghz Intel i3-6006u
RAM: 4GB (5GB Swap)
Kernel: 5.11.0-44-generic (x86_64 GNU/Linux)
DE: Gnome 3.36.9
WM: Mutter

### Commands
**Dependencies**
`sudo apt update && sudo apt upgrade`
`sudo apt install git npm` (probably already installed by default, can't really remember.)

**Compiling**
at your home path, run 
```
git clone https://github.com/ThePridestalker/OsuBackUp.git
```

then enter the directory with 
```
cd OsuBackUp
```

install all project dependencies with 
```
npm install
```

**(i did this, and i'm not sure if that's why it didn't work, pretty sure not.)** after that, run `npm audit fix` to fix all project's vulnerabilities.
then, 
```
npm update
```

to update packages at `packages.json` and then, build the project with: *(default among projects)*
```
npm run dist
```

after it finishes compiling, run 
```
./dist/OsuBackUp\ 1.0.0.AppImage
```
to run the `.AppImage` inside the **dist** folder.

## Info
Any questions or just for contact:
my Discord: `KarboX#9238`
[my Github page](https://github.com/KarboXXX)

**Comment by ThePridestalker** [comment]
Hey @KarboXXX, when I made this app, I used electron-builder, and I didn't add the required options to build the linux distribution. Probably there is a better builder now a days for electron, but I don't have the time to play around and find the answers needed.
I have checked the documentation of electron-builder, and the package.json needs the linux info to build it. I'm sure you can find the answer for me, and submit a pull request with the package.json changes.

**Comment by KarboXXX** [comment]
Hey @ThePridestalker, i'm working on it already (nothing to do, but pretty good project tho), i'll test compiling the project on Arch Linux too. And i was wondering if you would like a `pt_BR` translation, since i'm a brazilian native speaker. (i don't know how you would apply it, so it would be a file with all strings organized)

At the moment, i change the final lines at `README.md` to explain the compiling process since installing dependencies for both Windows and Linux operating systems and explaining details. Changed `package.json` as you said, and understanding how your JS scripts and trying to improve them if possible!

I'll make the pull request when done! Can i add a contributors variable at package.json with my github page? :)

**Comment by KarboXXX** [comment]
Updates, got it to run on Linux without problems, compiling is 2% faster without optimizations
